### ISSUE TITLE
Silencer not working

### ISSUE THREAD

**Issue by antarr** [stve/silencer#28]
I've added silencer to my rails 4.2 application and it is not working. I'm trying to omit things coming from gems.  I've added this initializer

**config/intiailizers/silencer.rb**
```
Rails.application.configure do
  config.middleware.swap(
    Rails::Rack::Logger,
    Silencer::Logger,
    config.log_tags,
    silence: [%r{^/var/lib/gems/}]
  )
end

```
And I'm still get logs like this

```
17:10:47 web.1         | /var/lib/gems/2.6.0/gems/rack-cors-1.0.6/lib/rack/cors.rb:98:in `call'
17:10:47 web.1         | /var/lib/gems/2.6.0/gems/rack-cors-1.0.6/lib/rack/cors.rb:98:in `call'
17:10:47 web.1         | /var/lib/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/engine.rb:518:in `call'
17:10:47 web.1         | /var/lib/gems/2.6.0/gems/railties-4.2.11.1/lib/rails/application.rb:165:in `call'
17:10:47 web.1         | /var/lib/gems/2.6.0/gems/rack-1.6.12/lib/rack/content_length.rb:15:in `call'
17:10:47 web.1         | /var/lib/gems/2.6.0/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
17:10:47 web.1         | /var/lib/gems/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
17:10:47 web.1         | /var/lib/gems/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
17:10:47 web.1         | /var/lib/gems/2.6.0/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
17:10:47 web.1         | /var/lib/gems/2.6.0/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by stve** [comment]
@antarr Sorry that I'm just responding to this and I hope you found a solution to the issue you were having. This gem isn't meant to accept a local filesystem path. Instead, it was intended for specifying URL paths in your application. I hope this helps!
