### ISSUE TITLE
RuntimeError: No such middleware to insert before: Rails::Rack::Logger

### ISSUE THREAD

**Issue by jhnvz** [stve/silencer#9]
I get an error starting application:

```
RuntimeError: No such middleware to insert before: Rails::Rack::Logger
~/.rvm/gems/ruby-1.9.2-p320@rentwall/gems/actionpack-3.2.15/lib/action_dispatch/middleware/stack.rb:120:in `assert_index'
~/.rvm/gems/ruby-1.9.2-p320@rentwall/gems/actionpack-3.2.15/lib/action_dispatch/middleware/stack.rb:96:in `swap'
~/apps/ruby/rentwall/config/environment.rb:9:in `<class:Application>'
~/apps/ruby/rentwall/config/environment.rb:8:in `<module:Rentwall>'
~/apps/ruby/rentwall/config/environment.rb:7:in `<top (required)>'
<internal:lib/rubygems/custom_require>:29:in `require'
<internal:lib/rubygems/custom_require>:29:in `require'
~/apps/ruby/rentwall/config.ru:3:in `block in <main>'
~/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/builder.rb:4:in `instance_eval'
~/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/builder.rb:4:in `initialize'
~/apps/ruby/rentwall/config.ru:1:in `new'
~/apps/ruby/rentwall/config.ru:1:in `<main>'
~/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:50:in `eval'
~/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:50:in `load_config'
~/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:43:in `initialize'
~/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:13:in `new'
~/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/nack/server.rb:13:in `run'
~/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/bin/nack_worker:4:in `<main>'
```

development.rb:

``` ruby
require 'silencer/logger'

Rentwall::Application.configure do
  config.middleware.swap Rails::Rack::Logger, Silencer::Logger, :silence => ["/alarm"]
end
```

Gemfile:

``` ruby
source 'https://rubygems.org'

## Core

gem 'rails', '3.2.15'

group :development do
  gem 'thin'
  gem 'sqlite3'
  gem 'zeus'
end

group :produciton do
  gem 'unicorn'
  gem 'mysql2'
end

## Background jobs

gem 'whenever', :require => false

## Image processing

gem 'paperclip'

## Test

group :test do
  ## HTTP requests
  gem 'webmock'
end

group :development, :test do
  gem "rspec-rails", "~> 2.0"
  gem 'shoulda-matchers'
  gem "database_cleaner"
  gem 'fuubar'

  ## Mocking

  gem 'factory_girl_rails'

  ## Integration

  gem 'launchy'
  gem 'capybara', '1.1.2'
  gem 'capybara-webkit'

  ## Simple coverage

  gem 'simplecov', :require => false

  ## Javascript

  gem 'teaspoon'

  ## Integration

  gem 'cucumber', '1.2.5'
  gem 'cucumber-rails', '1.3.0', :require => false

  ## Automation

  gem 'spork-rails'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-spork'
  gem 'guard-teaspoon'
  gem 'guard-cucumber'

  ## Notification

  gem 'rb-fsevent', '~> 0.9.1'
  gem 'sys-proctable'
  gem 'growl'
end

group :development do
  gem "factory_girl_rails"
  gem "rspec-rails", "~> 2.0"
  gem 'simplecov', :require => false
end

#Assets

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'execjs'
  gem 'therubyracer'
end
gem 'bourbon'
gem "haml", ">= 3.0.0"
gem "haml-rails"
gem 'jquery-rails'
gem 'jquery-ui-rails'


## Authentication

gem "devise"

## Other

gem 'mollie-sms'
gem 'psych'
gem 'httparty', '0.8.3'
gem 'hashie'
gem 'listen', '0.6.0'
gem 'silencer'

## Development

group :development do
  gem 'capistrano', '2.15.5'
  gem 'powder'
  gem 'zeus'
end
```

Gemfile.lock

``` yaml
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (3.2.15)
      actionpack (= 3.2.15)
      mail (~> 2.5.4)
    actionpack (3.2.15)
      activemodel (= 3.2.15)
      activesupport (= 3.2.15)
      builder (~> 3.0.0)
      erubis (~> 2.7.0)
      journey (~> 1.0.4)
      rack (~> 1.4.5)
      rack-cache (~> 1.2)
      rack-test (~> 0.6.1)
      sprockets (~> 2.2.1)
    activemodel (3.2.15)
      activesupport (= 3.2.15)
      builder (~> 3.0.0)
    activerecord (3.2.15)
      activemodel (= 3.2.15)
      activesupport (= 3.2.15)
      arel (~> 3.0.2)
      tzinfo (~> 0.3.29)
    activeresource (3.2.15)
      activemodel (= 3.2.15)
      activesupport (= 3.2.15)
    activesupport (3.2.15)
      i18n (~> 0.6, >= 0.6.4)
      multi_json (~> 1.0)
    addressable (2.3.5)
    arel (3.0.2)
    atomic (1.1.14)
    bcrypt-ruby (3.1.2)
    bourbon (3.1.8)
      sass (>= 3.2.0)
      thor
    builder (3.0.4)
    capistrano (2.15.5)
      highline
      net-scp (>= 1.0.0)
      net-sftp (>= 2.0.0)
      net-ssh (>= 2.0.14)
      net-ssh-gateway (>= 1.1.0)
    capybara (1.1.2)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      selenium-webdriver (~> 2.0)
      xpath (~> 0.1.4)
    capybara-webkit (0.13.1)
      capybara (>= 1.0.0, < 1.2)
      json
    childprocess (0.3.9)
      ffi (~> 1.0, >= 1.0.11)
    chronic (0.10.2)
    climate_control (0.0.3)
      activesupport (>= 3.0)
    cocaine (0.5.2)
      climate_control (>= 0.0.3, < 1.0)
    coderay (1.0.9)
    coffee-rails (3.2.2)
      coffee-script (>= 2.2.0)
      railties (~> 3.2.0)
    coffee-script (2.2.0)
      coffee-script-source
      execjs
    coffee-script-source (1.6.3)
    crack (0.4.1)
      safe_yaml (~> 0.9.0)
    cucumber (1.2.5)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.3)
      gherkin (~> 2.11.7)
      multi_json (~> 1.3)
    cucumber-rails (1.3.0)
      capybara (>= 1.1.2)
      cucumber (>= 1.1.8)
      nokogiri (>= 1.5.0)
    daemons (1.1.9)
    database_cleaner (1.2.0)
    devise (3.1.1)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    diff-lcs (1.2.4)
    erubis (2.7.0)
    eventmachine (1.0.3)
    execjs (2.0.2)
    factory_girl (4.2.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.2.1)
      factory_girl (~> 4.2.0)
      railties (>= 3.0.0)
    faye-websocket (0.4.7)
      eventmachine (>= 0.12.0)
    ffi (1.9.0)
    formatador (0.2.4)
    fuubar (1.2.1)
      rspec (~> 2.0)
      rspec-instafail (~> 0.2.0)
      ruby-progressbar (~> 1.0)
    gherkin (2.11.8)
      multi_json (~> 1.3)
    growl (1.0.3)
    guard (1.7.0)
      formatador (>= 0.2.4)
      listen (>= 0.6.0)
      lumberjack (>= 1.0.2)
      pry (>= 0.9.10)
      thor (>= 0.14.6)
    guard-cucumber (1.4.0)
      cucumber (>= 1.2.0)
      guard (>= 1.1.0)
    guard-rspec (2.5.4)
      guard (>= 1.1)
      rspec (~> 2.11)
    guard-spork (1.5.1)
      childprocess (>= 0.2.3)
      guard (>= 1.1)
      spork (>= 0.8.4)
    guard-teaspoon (0.0.4)
      guard (>= 1.6.1)
      teaspoon (>= 0.5.3)
    haml (4.0.3)
      tilt
    haml-rails (0.4)
      actionpack (>= 3.1, < 4.1)
      activesupport (>= 3.1, < 4.1)
      haml (>= 3.1, < 4.1)
      railties (>= 3.1, < 4.1)
    hashie (2.0.5)
    highline (1.6.20)
    hike (1.2.3)
    http_parser.rb (0.5.3)
    httparty (0.8.3)
      multi_json (~> 1.0)
      multi_xml
    i18n (0.6.5)
    journey (1.0.4)
    jquery-rails (3.0.4)
      railties (>= 3.0, < 5.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (4.0.5)
      railties (>= 3.1.0)
    json (1.8.1)
    kgio (2.8.1)
    launchy (2.3.0)
      addressable (~> 2.3)
    libv8 (3.16.14.3)
    listen (0.6.0)
    lumberjack (1.0.4)
    mail (2.5.4)
      mime-types (~> 1.16)
      treetop (~> 1.4.8)
    method_source (0.8.2)
    mime-types (1.25)
    mini_portile (0.5.1)
    mollie-sms (1.0.0)
      activesupport (>= 2.3.8)
    multi_json (1.8.2)
    multi_xml (0.5.5)
    mysql2 (0.3.13)
    net-scp (1.1.2)
      net-ssh (>= 2.6.5)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (2.7.0)
    net-ssh-gateway (1.2.0)
      net-ssh (>= 2.6.5)
    nokogiri (1.6.0)
      mini_portile (~> 0.5.0)
    orm_adapter (0.4.0)
    paperclip (3.5.1)
      activemodel (>= 3.0.0)
      activesupport (>= 3.0.0)
      cocaine (~> 0.5.0)
      mime-types
    phantomjs (1.8.1.1)
      poltergeist
    poltergeist (1.0.3)
      capybara (~> 1.1)
      childprocess (~> 0.3)
      faye-websocket (~> 0.4.4)
      http_parser.rb (~> 0.5.3)
      multi_json (~> 1.0)
    polyglot (0.3.3)
    powder (0.2.0)
      thor (>= 0.11.5)
    pry (0.9.12.2)
      coderay (~> 1.0.5)
      method_source (~> 0.8)
      slop (~> 3.4)
    psych (2.0.1)
    rack (1.4.5)
    rack-cache (1.2)
      rack (>= 0.4)
    rack-ssl (1.3.3)
      rack
    rack-test (0.6.2)
      rack (>= 1.0)
    rails (3.2.15)
      actionmailer (= 3.2.15)
      actionpack (= 3.2.15)
      activerecord (= 3.2.15)
      activeresource (= 3.2.15)
      activesupport (= 3.2.15)
      bundler (~> 1.0)
      railties (= 3.2.15)
    railties (3.2.15)
      actionpack (= 3.2.15)
      activesupport (= 3.2.15)
      rack-ssl (~> 1.3.2)
      rake (>= 0.8.7)
      rdoc (~> 3.4)
      thor (>= 0.14.6, < 2.0)
    raindrops (0.12.0)
    rake (10.1.0)
    rb-fsevent (0.9.3)
    rdoc (3.12.2)
      json (~> 1.4)
    ref (1.0.5)
    rspec (2.14.1)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    rspec-core (2.14.6)
    rspec-expectations (2.14.3)
      diff-lcs (>= 1.1.3, < 2.0)
    rspec-instafail (0.2.4)
    rspec-mocks (2.14.4)
    rspec-rails (2.14.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 2.14.0)
      rspec-expectations (~> 2.14.0)
      rspec-mocks (~> 2.14.0)
    ruby-progressbar (1.2.0)
    rubyzip (1.0.0)
    safe_yaml (0.9.7)
    sass (3.2.12)
    sass-rails (3.2.6)
      railties (~> 3.2.0)
      sass (>= 3.1.10)
      tilt (~> 1.3)
    selenium-webdriver (2.37.0)
      childprocess (>= 0.2.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0.0)
      websocket (~> 1.0.4)
    shoulda-matchers (2.4.0)
      activesupport (>= 3.0.0)
    silencer (0.6.0)
      railties (>= 3)
    simplecov (0.7.1)
      multi_json (~> 1.0)
      simplecov-html (~> 0.7.1)
    simplecov-html (0.7.1)
    slop (3.4.6)
    spork (1.0.0rc4)
    spork-rails (4.0.0)
      rails (>= 3.0.0, < 5)
      spork (>= 1.0rc0)
    sprockets (2.2.2)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sqlite3 (1.3.8)
    sys-proctable (0.9.3)
    teaspoon (0.7.7)
      phantomjs (>= 1.8.1.1)
      railties (>= 3.2.5, < 5)
    therubyracer (0.12.0)
      libv8 (~> 3.16.14.0)
      ref
    thin (1.5.1)
      daemons (>= 1.0.9)
      eventmachine (>= 0.12.6)
      rack (>= 1.0.0)
    thor (0.18.1)
    thread_safe (0.1.3)
      atomic
    tilt (1.4.1)
    treetop (1.4.15)
      polyglot
      polyglot (>= 0.3.1)
    tzinfo (0.3.38)
    uglifier (2.2.1)
      execjs (>= 0.3.0)
      multi_json (~> 1.0, >= 1.0.2)
    unicorn (4.6.3)
      kgio (~> 2.6)
      rack
      raindrops (~> 0.7)
    warden (1.2.3)
      rack (>= 1.0)
    webmock (1.15.0)
      addressable (>= 2.2.7)
      crack (>= 0.3.2)
    websocket (1.0.7)
    whenever (0.8.4)
      activesupport (>= 2.3.4)
      chronic (>= 0.6.3)
    xpath (0.1.4)
      nokogiri (~> 1.3)
    zeus (0.13.3)
      method_source (>= 0.6.7)

PLATFORMS
  ruby

DEPENDENCIES
  bourbon
  capistrano (= 2.15.5)
  capybara (= 1.1.2)
  capybara-webkit
  coffee-rails (~> 3.2.1)
  cucumber (= 1.2.5)
  cucumber-rails (= 1.3.0)
  database_cleaner
  devise
  execjs
  factory_girl_rails
  fuubar
  growl
  guard
  guard-cucumber
  guard-rspec
  guard-spork
  guard-teaspoon
  haml (>= 3.0.0)
  haml-rails
  hashie
  httparty (= 0.8.3)
  jquery-rails
  jquery-ui-rails
  launchy
  listen (= 0.6.0)
  mollie-sms
  mysql2
  paperclip
  powder
  psych
  rails (= 3.2.15)
  rb-fsevent (~> 0.9.1)
  rspec-rails (~> 2.0)
  sass-rails (~> 3.2.3)
  shoulda-matchers
  silencer
  simplecov
  spork-rails
  sqlite3
  sys-proctable
  teaspoon
  therubyracer
  thin
  uglifier (>= 1.0.3)
  unicorn
  webmock
  whenever
  zeus
```

**Comment by danarnold** [comment]
We're having the same issue on Rails 4.2.6 with 1.0.0.rc3.

**Comment by 6temes** [comment]
Not working neither with the same setup in Rails 5.0.0.1
